// <auto-generated />
namespace proiectLicenta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatela810 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatela810));
        
        string IMigrationMetadata.Id
        {
            get { return "201602201324264_update-la-810"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
