// <auto-generated />
namespace proiectLicenta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adaugaremigratierulareJobDateGithub : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adaugaremigratierulareJobDateGithub));
        
        string IMigrationMetadata.Id
        {
            get { return "201602272238005_adaugare-migratie-rulareJobDateGithub"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
