// <auto-generated />
namespace proiectLicenta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IX_Stack_Overflow_Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IX_Stack_Overflow_Id));
        
        string IMigrationMetadata.Id
        {
            get { return "201603041931283_IX_Stack_Overflow_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
